import test,{beforeEach,afterEach} from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';import {register} from 'node:module';
register('./ignoreStyles.mjs',import.meta.url);const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,localStorage:dom.window.localStorage,sessionStorage:dom.window.sessionStorage,CustomEvent:dom.window.CustomEvent,IS_REACT_ACT_ENVIRONMENT:true});
const {render,cleanup,screen,fireEvent,act}=await import('@testing-library/react');const {useState}=await import('react');const {QuizEditor}=await import('../src/components/LessonManager.jsx');const {establishSession,clearSession}=await import('../src/utils/authClient.js');
const quiz={title:'Generated Quiz',questions:Array.from({length:2},(_,i)=>({question:`Generated ${i}`,type:'multiple_choice',options:['A','B','C','D'],correctOption:2,media:null}))};let calls,respond,confirmCalls;
function Harness({initial=null,...props}){const [value,setValue]=useState(initial);return <QuizEditor courseId="course" lessonId="lesson" quiz={value} setQuiz={setValue} {...props}/>;}
beforeEach(()=>{establishSession({id:'tutor',role:'tutor'},'test');calls=[];confirmCalls=0;window.confirm=()=>{confirmCalls++;return true;};respond=async()=>new Response(JSON.stringify({quiz,generated:true,saved:false}),{status:200});globalThis.fetch=async(url,options)=>{calls.push({url,...options});return respond();};});afterEach(()=>{cleanup();clearSession();});
test('controls default to five, send chosen count, show loading and populate the existing editable editor without saving',async()=>{
 let finish;respond=()=>new Promise(resolve=>{finish=resolve;});render(<Harness/>);assert.equal(screen.getByLabelText('Number of questions').value,'5');fireEvent.change(screen.getByLabelText('Number of questions'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));assert.ok(screen.getByRole('button',{name:'Generating...'}).disabled);assert.deepEqual(JSON.parse(calls[0].body),{questionCount:2});
 await act(async()=>finish(new Response(JSON.stringify({quiz,saved:false}),{status:200})));const questions=screen.getAllByPlaceholderText('Type your question here');assert.equal(questions.length,2);fireEvent.change(questions[0],{target:{value:'Edited draft'}});assert.equal(screen.getAllByPlaceholderText('Type your question here')[0].value,'Edited draft');fireEvent.click(screen.getAllByRole('button',{name:'Delete'})[0]);assert.equal(screen.getAllByPlaceholderText('Type your question here').length,1);assert.equal(calls.length,1);assert.ok(calls[0].url.endsWith('/generate-quiz'));
});
test('replacement confirmation cancel preserves quiz; approval replaces it',async()=>{
 render(<Harness initial={{...quiz,title:'Original'}}/>);window.confirm=()=>{confirmCalls++;return false;};fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));assert.equal(calls.length,0);assert.equal(screen.getByDisplayValue('Original').value,'Original');window.confirm=()=>{confirmCalls++;return true;};fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));await screen.findByDisplayValue('Generated Quiz');assert.equal(confirmCalls,2);
});
test('unsaved material or new lessons disable generation; invalid counts rejected',()=>{
 const view=render(<Harness materialDirty/>);assert.ok(screen.getByRole('button',{name:'Generate with AI'}).disabled);assert.ok(screen.getByText('Save the lesson changes before generating a quiz.'));view.rerender(<Harness lessonId=""/>);assert.ok(screen.getByRole('button',{name:'Generate with AI'}).disabled);view.rerender(<Harness/>);for(const value of ['1','21','2.5']){fireEvent.change(screen.getByLabelText('Number of questions'),{target:{value}});assert.ok(screen.getByRole('button',{name:'Generate with AI'}).disabled);}assert.equal(calls.length,0);
});
test('backend error is displayed and concurrent edits are never overwritten',async()=>{
 respond=async()=>new Response(JSON.stringify({message:'Temporary usage limit'}),{status:429});const view=render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));await screen.findByText('Temporary usage limit');view.unmount();let finish;respond=()=>new Promise(resolve=>{finish=resolve;});render(<Harness initial={quiz}/>);fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));fireEvent.change(screen.getAllByPlaceholderText('Type your question here')[0],{target:{value:'Keep my edits'}});await act(async()=>finish(new Response(JSON.stringify({quiz}),{status:200})));await screen.findByText(/Your edits were kept/);assert.ok(screen.getByDisplayValue('Keep my edits'));
});

test('lesson material changes during generation discard the response; unmount aborts the request',async()=>{
 let finish;respond=()=>new Promise(resolve=>{finish=resolve;});const view=render(<Harness contextKey="saved-v1"/>);
 fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));view.rerender(<Harness contextKey="edited-v1" materialDirty/>);
 await act(async()=>finish(new Response(JSON.stringify({quiz}),{status:200})));await screen.findByText(/Your edits were kept/);assert.equal(screen.queryByDisplayValue('Generated Quiz'),null);
 view.rerender(<Harness contextKey="saved-v2"/>);fireEvent.click(screen.getByRole('button',{name:'Generate with AI'}));const signal=calls.at(-1).signal;view.unmount();assert.ok(signal.aborted);
});
