import { useEffect,useRef,useState } from "react";
import { FaCheck,FaEye,FaSearch,FaTimes,FaTrash } from "react-icons/fa";
import AdminLayout from "../components/AdminLayout";
import AdminListControls from "../components/AdminListControls";
import { adminApi,formatAdminDate } from "../utils/adminApi";
import { formatCoursePrice } from "../utils/courseApi";
import "../styles/AdminLayout.css";

const statusLabel=status=>status==="published"?"Approved":status==="pending"?"Pending":status==="rejected"?"Rejected":"Draft";
const simpleStatus=status=>status==="published"?"approved":status==="pending"?"pending":status==="rejected"?"rejected":"draft";
const complete=course=>Boolean(course.name?.trim()&&course.description?.trim()&&course.category?.trim()&&course.tutor&&course.lessons?.length&&course.lessons.every(lesson=>lesson.title?.trim()&&(lesson.primaryMedia?.storedName||lesson.videoUrl?.trim()||lesson.resources?.length||lesson.references?.length)));

export default function AdminCourses(){
 const [courses,setCourses]=useState([]),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[message,setMessage]=useState(""),[viewCourse,setViewCourse]=useState(null),[confirmation,setConfirmation]=useState(null),[visible,setVisible]=useState(5);
 const load=async()=>{const items=await adminApi("/courses");setCourses(items);setViewCourse(current=>current?items.find(item=>item._id===current._id)||null:null)};
 useEffect(()=>{const timer=setTimeout(()=>adminApi("/courses").then(setCourses).catch(error=>setMessage(error.message)),0);return()=>clearTimeout(timer)},[]);
 const moderate=async(course,moderationStatus,feedback="")=>{await adminApi(`/courses/${course._id}/moderation`,{method:"PATCH",body:JSON.stringify({moderationStatus,feedback})});await load();setMessage(moderationStatus==="published"?`${course.name} was approved and is now visible to students.`:`${course.name} was rejected and the tutor was notified.`);if(moderationStatus==="rejected")setViewCourse(null)};
 const updatePrice=async(course,price)=>{const numericPrice=Number(price);if(price===""||!Number.isFinite(numericPrice)||numericPrice<0){throw new Error("Enter a valid price of 0 or more.")}const updated=await adminApi(`/courses/${course._id}`,{method:"PATCH",body:JSON.stringify({price:numericPrice})});await load();setMessage(`${course.name} price updated to ${formatCoursePrice(numericPrice)}.`);return updated};
 const remove=async course=>{await adminApi(`/courses/${course._id}`,{method:"DELETE"});await load();setMessage(`${course.name} was permanently deleted.`);setViewCourse(null)};
 const filtered=courses.filter(course=>`${course.name} ${course.tutor?.name||""} ${course.category}`.toLowerCase().includes(search.trim().toLowerCase())&&(status==="all"||simpleStatus(course.moderationStatus)===status));
 return <AdminLayout title="Course Management">{message&&<div className="adm-card">{message}</div>}<section className="adm-card"><div className="adm-card-hdr"><div><span className="adm-card-title">Courses</span><p className="adm-muted">{courses.filter(course=>course.moderationStatus==="pending").length} waiting for approval</p></div></div><div className="adm-search-row"><label className="adm-search-box"><FaSearch/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search by course, tutor, or category"/></label><select className="adm-select" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="draft">Draft</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div><div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Course</th><th>Tutor</th><th>Category</th><th>Lessons</th><th>Enrollments</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{filtered.slice(0,visible).map(course=><CourseRow key={course._id} course={course} view={setViewCourse} confirm={setConfirmation}/>)}</tbody></table></div>{!filtered.length&&<p className="adm-empty">No courses match this filter.</p>}<AdminListControls total={filtered.length} visible={visible} onChange={setVisible}/></section>{viewCourse&&<CourseView course={viewCourse} close={()=>setViewCourse(null)} confirm={setConfirmation} savePrice={updatePrice}/>} {confirmation&&<ConfirmDialog value={confirmation} cancel={()=>setConfirmation(null)} submit={feedback=>confirmation.type==="delete"?remove(confirmation.course):moderate(confirmation.course,confirmation.type==="approve"?"published":"rejected",feedback)}/>}</AdminLayout>
}

function CourseRow({course,view,confirm}){const approved=course.moderationStatus==="published",pending=course.moderationStatus==="pending",canApprove=pending&&complete(course);return <tr><td><strong>{course.name}</strong><div className="adm-muted adm-course-description">{course.description}</div></td><td>{course.tutor?<><strong>{course.tutor.name}</strong><div className="adm-muted">{course.tutor.email}</div></>:<span className="adm-warning-text">Unassigned</span>}</td><td>{course.category}</td><td>{course.lessons?.length||0}</td><td>{course.students||0}</td><td><span className={`adm-status-pill pill-${simpleStatus(course.moderationStatus)}`}>{statusLabel(course.moderationStatus)}</span></td><td className="adm-muted">{formatAdminDate(course.updatedAt)}</td><td><div className="adm-action-row adm-course-actions"><button className="adm-btn adm-btn-secondary adm-btn-sm" onClick={()=>view(course)}><FaEye/> View</button>{approved?<span className="adm-approved-action"><FaCheck/> Approved</span>:<button className="adm-btn adm-btn-success adm-btn-sm" disabled={!canApprove} title={canApprove?"Approve course":"Only complete pending courses can be approved"} onClick={()=>confirm({type:"approve",course})}><FaCheck/> Approve</button>}<button className="adm-btn adm-btn-danger adm-btn-sm" disabled={!pending} title={pending?"Reject course":"Only pending courses can be rejected"} onClick={()=>confirm({type:"reject",course})}><FaTimes/> Reject</button><button className="adm-btn adm-btn-danger adm-btn-sm" onClick={()=>confirm({type:"delete",course})}><FaTrash/> Delete</button></div></td></tr>}

function CourseView({course,close,confirm,savePrice}){
 const canApprove=course.moderationStatus==="pending"&&complete(course),[price,setPrice]=useState(String(course.price??0)),[savingPrice,setSavingPrice]=useState(false),[priceError,setPriceError]=useState("");
 const submitPrice=async event=>{event.preventDefault();setSavingPrice(true);setPriceError("");try{const updated=await savePrice(course,price);setPrice(String(updated.price??0))}catch(error){setPriceError(error.message)}finally{setSavingPrice(false)}};
 return <div className="adm-modal-backdrop" role="presentation" onMouseDown={close}><section className="adm-review-modal adm-course-view" role="dialog" aria-modal="true" aria-labelledby="course-view-title" onMouseDown={event=>event.stopPropagation()}>
  <header className="adm-review-header"><div><span>COURSE PREVIEW</span><h2 id="course-view-title">{course.name}</h2><p>{course.description}</p></div><button className="adm-modal-close" aria-label="Close preview" onClick={close}><FaTimes/></button></header>
  <div className="adm-course-preview-cover">{course.thumbnail?<img src={course.thumbnail} alt={course.name}/>:<span>No course image</span>}</div>
  <div className="adm-review-summary"><div><small>Tutor</small><strong>{course.tutor?.name||"Unassigned"}</strong></div><div><small>Category</small><strong>{course.category}</strong></div><div><small>Difficulty</small><strong>{course.level}</strong></div><div><small>Status</small><strong>{statusLabel(course.moderationStatus)}</strong></div><div><small>Current price</small><strong>{formatCoursePrice(course.price)}</strong></div></div>
  <form className="adm-price-form" onSubmit={submitPrice}><label><span>Course price (THB)</span><input type="number" min="0" step="0.01" required value={price} onChange={event=>setPrice(event.target.value)} aria-describedby="course-price-help"/></label><small id="course-price-help">Use 0 for a free course. The saved numeric price is used at checkout.</small>{priceError&&<p>{priceError}</p>}<button className="adm-btn adm-btn-secondary" disabled={savingPrice}>{savingPrice?"Saving...":"Save price"}</button></form>
  <h3>Course content</h3><div className="adm-lesson-review-list">{course.lessons?.map((lesson,index)=><article key={lesson._id||index}><span>{String(index+1).padStart(2,"0")}</span><div><strong>{lesson.title}</strong><p>{lesson.description||"No lesson description"} · {lesson.duration||"Duration unavailable"}</p>{lesson.summary&&<p><b>Tutor summary:</b> {lesson.summary}</p>}{lesson.transcript&&<p><b>Transcript provided</b></p>}{lesson.videoUrl&&<a href={lesson.videoUrl} target="_blank" rel="noreferrer">Open lesson content</a>}{lesson.resources?.map(resource=><a key={resource.url} href={resource.url} target="_blank" rel="noreferrer">{resource.originalName}</a>)}</div></article>)}{!course.lessons?.length&&<p className="adm-empty">No lessons have been added.</p>}</div>
  {course.moderationStatus==="pending"&&<footer className="adm-review-actions"><button className="adm-btn adm-btn-danger" onClick={()=>confirm({type:"reject",course})}><FaTimes/> Reject</button><button className="adm-btn adm-btn-success" disabled={!canApprove} onClick={()=>confirm({type:"approve",course})}><FaCheck/> Approve</button></footer>}
 </section></div>
}
export function ConfirmDialog({value,cancel,submit}){
 const approve=value.type==="approve",deleting=value.type==="delete",[feedback,setFeedback]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),dialogRef=useRef(null),submittingRef=useRef(false),returnFocusRef=useRef(document.activeElement);
 useEffect(()=>{const dialog=dialogRef.current,returnFocus=returnFocusRef.current,focusable=()=>[...dialog.querySelectorAll('button:not([disabled]),textarea:not([disabled])')];focusable()[0]?.focus();const keydown=event=>{if(event.key==="Escape"){event.preventDefault();if(!submittingRef.current)cancel();return}if(event.key!=="Tab")return;const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",keydown);return()=>{document.removeEventListener("keydown",keydown);returnFocus?.focus?.()}},[cancel]);
 const run=async event=>{event.preventDefault();if(submittingRef.current)return;submittingRef.current=true;setLoading(true);setError("");try{await submit(feedback);cancel()}catch(requestError){setError(requestError.message||"The request failed. Please try again.");submittingRef.current=false;setLoading(false)}};
 const close=()=>{if(!submittingRef.current)cancel()};
 return <div className="adm-modal-backdrop" role="presentation" onMouseDown={close}><form ref={dialogRef} className="adm-confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="confirm-course-title" aria-busy={loading} onSubmit={run} onMouseDown={event=>event.stopPropagation()}><button type="button" className="adm-confirm-close" aria-label={approve?"Close approval dialog":"Close confirmation dialog"} onClick={close} disabled={loading}><FaTimes/></button><h2 id="confirm-course-title">{approve?"Approve Course?":deleting?"Delete Course?":"Reject Course"}</h2><p>{approve?<>Approve <strong>“{value.course.name}”</strong> and make it visible to students?</>:deleting?<>Are you sure you want to permanently delete <strong>“{value.course.name}”</strong>?</>:<>Course: <strong>{value.course.name}</strong><br/>Please tell the tutor why this course was rejected.</>}</p>{deleting&&<small>This action cannot be undone.</small>}{!approve&&!deleting&&<label className="adm-rejection-field"><span>Reason / Feedback</span><textarea required minLength="3" value={feedback} disabled={loading} onChange={event=>setFeedback(event.target.value)} placeholder="Explain what the tutor should improve before resubmitting."/></label>}{error&&<p className="adm-confirm-error" role="alert">{error}</p>}<footer><button type="button" className="adm-btn adm-btn-secondary" onClick={close} disabled={loading}>Cancel</button><button className={`adm-btn ${approve?"adm-btn-success":"adm-btn-danger"}`} disabled={loading||(!approve&&!deleting&&!feedback.trim())}>{loading?(approve?"Approving...":"Processing..."):approve?"Approve":deleting?"Delete":"Reject Course"}</button></footer></form></div>
}
